export const CATEGORY_OPTIONS = [
  "All Fields",
  "Computer Science",
  "Medicine",
  "Chemistry",
  "Biology",
  "Materials Science",
  "Physics",
  "Geology",
  "Psychology",
  "Art",
  "History",
  "Geography",
  "Sociology",
  "Business",
  "Political Science",
  "Economics",
  "Philosophy",
  "Mathematics",
  "Engineering",
  "Environmental Science",
  "Agricultural and Food Sciences",
  "Education",
  "Law",
  "Linguistics"
];

export const PRESET_KEYWORDS = [
  'LLM',
  'Agent',
  'RAG',
  'Prompt Engineering',
  'Quantum Computing',
  'Solid-State Battery',
  'Renewable Energy',
  'Autonomous Driving',
  'Computer Vision',
  'Neuroscience',
  'Virology',
  'Fintech',
  'V2G',
  'Edge Computing',
  'HCI',
  'Transformers',
  'NLP',
  'Robotics',
  'Bioinformatics',
  'Microplastics',
];
