export const CATEGORY_OPTIONS = [
  "All Fields",
  "Agricultural and Food Sciences",
  "Art",
  "Biology",
  "Business",
  "Chemistry",
  "Computer Science",
  "Economics",
  "Education",
  "Engineering",
  "Environmental Science",
  "Geography",
  "Geology",
  "History",
  "Law",
  "Linguistics",
  "Materials Science",
  "Mathematics",
  "Medicine",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Sociology"
];

export const PRESET_KEYWORDS = [
  'LLM',
  'Agent',
  'RAG',
  'Prompt Engineering',
  'Quantum Computing',
  'Solid-State Battery',
  'Renewable Energy',
  'Autonomous Driving',
  'Computer Vision',
  'Neuroscience',
  'Virology',
  'Fintech',
  'V2G',
  'Edge Computing',
  'HCI',
  'Transformers',
  'NLP',
  'Robotics',
  'Bioinformatics',
  'Microplastics',
];
